services:
  api:
    build: .  # chemin vers ton projet API
    container_name: api
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      VIRTUAL_HOST: api.saumondeluxe.com
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: api.saumondeluxe.com
      LETSENCRYPT_EMAIL: planque.adam@gmail.com
    networks:
      - proxy-tier
    env_file:
        - .env  # Charger les variables d'environnement depuis le fichier .env

networks:
  proxy-tier:
    external: true
